{% set name = "djangorestframework-jwt" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5efe33032f3a4518a300dc51a51c92145ad95fb6f4b272e5aa24701db67936a7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.8
    - djangorestframework >=3.1,<4
    - pyjwt >=1.5.2,<2

test:
  requires:
    - python {{ python_min }}
  imports:
    - rest_framework_jwt
    
about:
  home: https://github.com/GetBlimp/django-rest-framework-jwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'JSON Web Token Authentication support for Django REST Framework'
  description: 
    JSON Web Token Authentication support for Django REST Framework
  doc_url: https://getblimp.github.io/django-rest-framework-jwt/
  dev_url: https://github.com/GetBlimp/django-rest-framework-jwt

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
